import dotenv from 'dotenv'
import path from 'path'

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') })
dotenv.config({ path: path.resolve(process.cwd(), '.env') })

import { connectDB } from '../lib/db'
import Stock from '../models/Stock'

const NSE_STOCKS = [
  { symbol: 'RELIANCE', name: 'Reliance Industries Ltd', sector: 'Energy' },
  { symbol: 'TCS', name: 'Tata Consultancy Services Ltd', sector: 'IT' },
  { symbol: 'HDFCBANK', name: 'HDFC Bank Ltd', sector: 'Banking' },
  { symbol: 'INFY', name: 'Infosys Ltd', sector: 'IT' },
  { symbol: 'ICICIBANK', name: 'ICICI Bank Ltd', sector: 'Banking' },
  { symbol: 'HINDUNILVR', name: 'Hindustan Unilever Ltd', sector: 'FMCG' },
  { symbol: 'ITC', name: 'ITC Ltd', sector: 'FMCG' },
  { symbol: 'SBIN', name: 'State Bank of India', sector: 'Banking' },
  { symbol: 'BHARTIARTL', name: 'Bharti Airtel Ltd', sector: 'Telecom' },
  { symbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank Ltd', sector: 'Banking' },
  { symbol: 'LT', name: 'Larsen & Toubro Ltd', sector: 'Infrastructure' },
  { symbol: 'AXISBANK', name: 'Axis Bank Ltd', sector: 'Banking' },
  { symbol: 'ASIANPAINT', name: 'Asian Paints Ltd', sector: 'Consumer Goods' },
  { symbol: 'MARUTI', name: 'Maruti Suzuki India Ltd', sector: 'Automobile' },
  { symbol: 'TITAN', name: 'Titan Company Ltd', sector: 'Consumer Goods' },
  { symbol: 'SUNPHARMA', name: 'Sun Pharmaceutical Industries Ltd', sector: 'Pharma' },
  { symbol: 'ULTRACEMCO', name: 'UltraTech Cement Ltd', sector: 'Cement' },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance Ltd', sector: 'Finance' },
  { symbol: 'NESTLEIND', name: 'Nestle India Ltd', sector: 'FMCG' },
  { symbol: 'WIPRO', name: 'Wipro Ltd', sector: 'IT' },
  { symbol: 'HCLTECH', name: 'HCL Technologies Ltd', sector: 'IT' },
  { symbol: 'TECHM', name: 'Tech Mahindra Ltd', sector: 'IT' },
  { symbol: 'POWERGRID', name: 'Power Grid Corporation of India Ltd', sector: 'Power' },
  { symbol: 'NTPC', name: 'NTPC Ltd', sector: 'Power' },
  { symbol: 'ONGC', name: 'Oil and Natural Gas Corporation Ltd', sector: 'Energy' },
  { symbol: 'TATASTEEL', name: 'Tata Steel Ltd', sector: 'Metals' },
  { symbol: 'JSWSTEEL', name: 'JSW Steel Ltd', sector: 'Metals' },
  { symbol: 'HINDALCO', name: 'Hindalco Industries Ltd', sector: 'Metals' },
  { symbol: 'COALINDIA', name: 'Coal India Ltd', sector: 'Mining' },
  {
    symbol: 'ADANIPORTS',
    name: 'Adani Ports and Special Economic Zone Ltd',
    sector: 'Infrastructure',
  },
  { symbol: 'TATAMOTORS', name: 'Tata Motors Ltd', sector: 'Automobile' },
  { symbol: 'M&M', name: 'Mahindra & Mahindra Ltd', sector: 'Automobile' },
  { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv Ltd', sector: 'Finance' },
  { symbol: 'BAJAJ-AUTO', name: 'Bajaj Auto Ltd', sector: 'Automobile' },
  { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp Ltd', sector: 'Automobile' },
  { symbol: 'EICHERMOT', name: 'Eicher Motors Ltd', sector: 'Automobile' },
  { symbol: 'DIVISLAB', name: "Divi's Laboratories Ltd", sector: 'Pharma' },
  { symbol: 'DRREDDY', name: "Dr. Reddy's Laboratories Ltd", sector: 'Pharma' },
  { symbol: 'CIPLA', name: 'Cipla Ltd', sector: 'Pharma' },
  { symbol: 'APOLLOHOSP', name: 'Apollo Hospitals Enterprise Ltd', sector: 'Healthcare' },
  { symbol: 'GRASIM', name: 'Grasim Industries Ltd', sector: 'Cement' },
  { symbol: 'SHREECEM', name: 'Shree Cement Ltd', sector: 'Cement' },
  { symbol: 'BRITANNIA', name: 'Britannia Industries Ltd', sector: 'FMCG' },
  { symbol: 'DABUR', name: 'Dabur India Ltd', sector: 'FMCG' },
  { symbol: 'GODREJCP', name: 'Godrej Consumer Products Ltd', sector: 'FMCG' },
  { symbol: 'MARICO', name: 'Marico Ltd', sector: 'FMCG' },
  { symbol: 'PIDILITIND', name: 'Pidilite Industries Ltd', sector: 'Chemicals' },
  { symbol: 'INDUSINDBK', name: 'IndusInd Bank Ltd', sector: 'Banking' },
  { symbol: 'BANDHANBNK', name: 'Bandhan Bank Ltd', sector: 'Banking' },
  { symbol: 'SBILIFE', name: 'SBI Life Insurance Company Ltd', sector: 'Insurance' },
  { symbol: 'HDFCLIFE', name: 'HDFC Life Insurance Company Ltd', sector: 'Insurance' },
  {
    symbol: 'ICICIPRULI',
    name: 'ICICI Prudential Life Insurance Company Ltd',
    sector: 'Insurance',
  },
  { symbol: 'BAJAJHLDNG', name: 'Bajaj Holdings & Investment Ltd', sector: 'Finance' },
  { symbol: 'ADANIENT', name: 'Adani Enterprises Ltd', sector: 'Conglomerate' },
  { symbol: 'ADANIGREEN', name: 'Adani Green Energy Ltd', sector: 'Power' },
  { symbol: 'ADANITRANS', name: 'Adani Transmission Ltd', sector: 'Power' },
  { symbol: 'VEDL', name: 'Vedanta Ltd', sector: 'Metals' },
  { symbol: 'BPCL', name: 'Bharat Petroleum Corporation Ltd', sector: 'Energy' },
  { symbol: 'IOC', name: 'Indian Oil Corporation Ltd', sector: 'Energy' },
  { symbol: 'GAIL', name: 'GAIL (India) Ltd', sector: 'Energy' },
  { symbol: 'TATACONSUM', name: 'Tata Consumer Products Ltd', sector: 'FMCG' },
  { symbol: 'TATAPOWER', name: 'Tata Power Company Ltd', sector: 'Power' },
  { symbol: 'SIEMENS', name: 'Siemens Ltd', sector: 'Engineering' },
  { symbol: 'BOSCHLTD', name: 'Bosch Ltd', sector: 'Automobile' },
  { symbol: 'HAVELLS', name: 'Havells India Ltd', sector: 'Consumer Goods' },
  { symbol: 'VOLTAS', name: 'Voltas Ltd', sector: 'Consumer Goods' },
  { symbol: 'AMBUJACEM', name: 'Ambuja Cements Ltd', sector: 'Cement' },
  { symbol: 'ACC', name: 'ACC Ltd', sector: 'Cement' },
  { symbol: 'DLF', name: 'DLF Ltd', sector: 'Real Estate' },
  { symbol: 'GODREJPROP', name: 'Godrej Properties Ltd', sector: 'Real Estate' },
  { symbol: 'OBEROIRLTY', name: 'Oberoi Realty Ltd', sector: 'Real Estate' },
  { symbol: 'MCDOWELL-N', name: 'United Spirits Ltd', sector: 'FMCG' },
  { symbol: 'UBL', name: 'United Breweries Ltd', sector: 'FMCG' },
  { symbol: 'COLPAL', name: 'Colgate-Palmolive (India) Ltd', sector: 'FMCG' },
  { symbol: 'BERGEPAINT', name: 'Berger Paints India Ltd', sector: 'Consumer Goods' },
  { symbol: 'INDIGO', name: 'InterGlobe Aviation Ltd', sector: 'Aviation' },
  { symbol: 'ZOMATO', name: 'Zomato Ltd', sector: 'Technology' },
  { symbol: 'PAYTM', name: 'One 97 Communications Ltd', sector: 'Technology' },
  { symbol: 'NYKAA', name: 'FSN E-Commerce Ventures Ltd', sector: 'E-commerce' },
  { symbol: 'DMART', name: 'Avenue Supermarts Ltd', sector: 'Retail' },
  { symbol: 'TRENT', name: 'Trent Ltd', sector: 'Retail' },
  { symbol: 'JUBLFOOD', name: 'Jubilant FoodWorks Ltd', sector: 'Food Services' },
  { symbol: 'PVR', name: 'PVR Ltd', sector: 'Entertainment' },
  { symbol: 'MPHASIS', name: 'Mphasis Ltd', sector: 'IT' },
  { symbol: 'LTIM', name: 'LTIMindtree Ltd', sector: 'IT' },
  { symbol: 'PERSISTENT', name: 'Persistent Systems Ltd', sector: 'IT' },
  { symbol: 'COFORGE', name: 'Coforge Ltd', sector: 'IT' },
  { symbol: 'MINDTREE', name: 'Mindtree Ltd', sector: 'IT' },
  { symbol: 'MUTHOOTFIN', name: 'Muthoot Finance Ltd', sector: 'Finance' },
  {
    symbol: 'CHOLAFIN',
    name: 'Cholamandalam Investment and Finance Company Ltd',
    sector: 'Finance',
  },
  { symbol: 'LICHSGFIN', name: 'LIC Housing Finance Ltd', sector: 'Finance' },
  { symbol: 'PFC', name: 'Power Finance Corporation Ltd', sector: 'Finance' },
  { symbol: 'RECLTD', name: 'REC Ltd', sector: 'Finance' },
  {
    symbol: 'IRCTC',
    name: 'Indian Railway Catering and Tourism Corporation Ltd',
    sector: 'Tourism',
  },
  { symbol: 'CONCOR', name: 'Container Corporation of India Ltd', sector: 'Logistics' },
  { symbol: 'ABFRL', name: 'Aditya Birla Fashion and Retail Ltd', sector: 'Retail' },
  { symbol: 'PAGEIND', name: 'Page Industries Ltd', sector: 'Textile' },
  { symbol: 'DIXON', name: 'Dixon Technologies (India) Ltd', sector: 'Electronics' },
  
  // Additional Large & Mid Cap Stocks
  { symbol: 'UPL', name: 'UPL Ltd', sector: 'Chemicals' },
  { symbol: 'SAIL', name: 'Steel Authority of India Ltd', sector: 'Metals' },
  { symbol: 'NMDC', name: 'NMDC Ltd', sector: 'Mining' },
  { symbol: 'JINDALSTEL', name: 'Jindal Steel & Power Ltd', sector: 'Metals' },
  { symbol: 'CANBK', name: 'Canara Bank', sector: 'Banking' },
  { symbol: 'PNB', name: 'Punjab National Bank', sector: 'Banking' },
  { symbol: 'BANKBARODA', name: 'Bank of Baroda', sector: 'Banking' },
  { symbol: 'UNIONBANK', name: 'Union Bank of India', sector: 'Banking' },
  { symbol: 'IDFCFIRSTB', name: 'IDFC First Bank Ltd', sector: 'Banking' },
  { symbol: 'FEDERALBNK', name: 'Federal Bank Ltd', sector: 'Banking' },
  { symbol: 'RBLBANK', name: 'RBL Bank Ltd', sector: 'Banking' },
  { symbol: 'YESBANK', name: 'Yes Bank Ltd', sector: 'Banking' },
  { symbol: 'IDEA', name: 'Vodafone Idea Ltd', sector: 'Telecom' },
  { symbol: 'BHARATFORG', name: 'Bharat Forge Ltd', sector: 'Automobile' },
  { symbol: 'MOTHERSUMI', name: 'Motherson Sumi Systems Ltd', sector: 'Automobile' },
  { symbol: 'ESCORTS', name: 'Escorts Ltd', sector: 'Automobile' },
  { symbol: 'TVSMOTOR', name: 'TVS Motor Company Ltd', sector: 'Automobile' },
  { symbol: 'ASHOKLEY', name: 'Ashok Leyland Ltd', sector: 'Automobile' },
  { symbol: 'EXIDEIND', name: 'Exide Industries Ltd', sector: 'Automobile' },
  { symbol: 'MRF', name: 'MRF Ltd', sector: 'Automobile' },
  { symbol: 'APOLLOTYRE', name: 'Apollo Tyres Ltd', sector: 'Automobile' },
  { symbol: 'BALKRISIND', name: 'Balkrishan Industries Ltd', sector: 'Automobile' },
  { symbol: 'CUMMINSIND', name: 'Cummins India Ltd', sector: 'Automobile' },
  { symbol: 'LUPIN', name: 'Lupin Ltd', sector: 'Pharma' },
  { symbol: 'BIOCON', name: 'Biocon Ltd', sector: 'Pharma' },
  { symbol: 'CADILAHC', name: 'Cadila Healthcare Ltd', sector: 'Pharma' },
  { symbol: 'AUROPHARMA', name: 'Aurobindo Pharma Ltd', sector: 'Pharma' },
  { symbol: 'TORNTPHARM', name: 'Torrent Pharmaceuticals Ltd', sector: 'Pharma' },
  { symbol: 'ALKEM', name: 'Alkem Laboratories Ltd', sector: 'Pharma' },
  { symbol: 'LALPATHLAB', name: 'Dr Lal PathLabs Ltd', sector: 'Healthcare' },
  { symbol: 'METROPOLIS', name: 'Metropolis Healthcare Ltd', sector: 'Healthcare' },
  { symbol: 'FORTIS', name: 'Fortis Healthcare Ltd', sector: 'Healthcare' },
  { symbol: 'MAXHEALTH', name: 'Max Healthcare Institute Ltd', sector: 'Healthcare' },
  { symbol: 'RAMCOCEM', name: 'Ramco Cements Ltd', sector: 'Cement' },
  { symbol: 'JKCEMENT', name: 'JK Cement Ltd', sector: 'Cement' },
  { symbol: 'STARCEMENT', name: 'Star Cement Ltd', sector: 'Cement' },
  { symbol: 'HEIDELBERG', name: 'HeidelbergCement India Ltd', sector: 'Cement' },
  { symbol: 'DEEPAKNTR', name: 'Deepak Nitrite Ltd', sector: 'Chemicals' },
  { symbol: 'SRF', name: 'SRF Ltd', sector: 'Chemicals' },
  { symbol: 'AARTI', name: 'Aarti Industries Ltd', sector: 'Chemicals' },
  { symbol: 'GNFC', name: 'Gujarat Narmada Valley Fertilizers Company Ltd', sector: 'Chemicals' },
  { symbol: 'CHAMBLFERT', name: 'Chambal Fertilizers & Chemicals Ltd', sector: 'Chemicals' },
  { symbol: 'COROMANDEL', name: 'Coromandel International Ltd', sector: 'Chemicals' },
  { symbol: 'RALLIS', name: 'Rallis India Ltd', sector: 'Chemicals' },
  { symbol: 'BASF', name: 'BASF India Ltd', sector: 'Chemicals' },
  { symbol: 'AKZOINDIA', name: 'Akzo Nobel India Ltd', sector: 'Chemicals' },
  { symbol: 'KANSAINER', name: 'Kansai Nerolac Paints Ltd', sector: 'Consumer Goods' },
  { symbol: 'CROMPTON', name: 'Crompton Greaves Consumer Electricals Ltd', sector: 'Consumer Goods' },
  { symbol: 'VGUARD', name: 'V-Guard Industries Ltd', sector: 'Consumer Goods' },
  { symbol: 'WHIRLPOOL', name: 'Whirlpool of India Ltd', sector: 'Consumer Goods' },
  { symbol: 'BLUESTAR', name: 'Blue Star Ltd', sector: 'Consumer Goods' },
  { symbol: 'AMBER', name: 'Amber Enterprises India Ltd', sector: 'Consumer Goods' },
  { symbol: 'RELAXO', name: 'Relaxo Footwears Ltd', sector: 'Consumer Goods' },
  { symbol: 'BATAINDIA', name: 'Bata India Ltd', sector: 'Consumer Goods' },
  { symbol: 'VBL', name: 'Varun Beverages Ltd', sector: 'FMCG' },
  { symbol: 'RADICO', name: 'Radico Khaitan Ltd', sector: 'FMCG' },
  { symbol: 'CCL', name: 'CCL Products (India) Ltd', sector: 'FMCG' },
  { symbol: 'EMAMILTD', name: 'Emami Ltd', sector: 'FMCG' },
  { symbol: 'JYOTHYLAB', name: 'Jyothy Labs Ltd', sector: 'FMCG' },
  { symbol: 'GILLETTE', name: 'Gillette India Ltd', sector: 'FMCG' },
  { symbol: 'HONASA', name: 'Honasa Consumer Ltd', sector: 'FMCG' },
  { symbol: 'WESTLIFE', name: 'Westlife Development Ltd', sector: 'Food Services' },
  { symbol: 'DEVYANI', name: 'Devyani International Ltd', sector: 'Food Services' },
  { symbol: 'SAPPHIRE', name: 'Sapphire Foods India Ltd', sector: 'Food Services' },
  { symbol: 'SHOPERSTOP', name: 'Shoppers Stop Ltd', sector: 'Retail' },
  { symbol: 'SPENCERS', name: 'Spencer\'s Retail Ltd', sector: 'Retail' },
  { symbol: 'AHLWEST', name: 'Ahluwalia Contracts (India) Ltd', sector: 'Construction' },
  { symbol: 'JKLAKSHMI', name: 'JK Lakshmi Cement Ltd', sector: 'Cement' },
  { symbol: 'ORIENTCEM', name: 'Orient Cement Ltd', sector: 'Cement' },
  { symbol: 'PRISMJOHNSN', name: 'Prism Johnson Ltd', sector: 'Cement' },
  { symbol: 'JBCHEPHARM', name: 'JB Chemicals & Pharmaceuticals Ltd', sector: 'Pharma' },
  { symbol: 'GRANULES', name: 'Granules India Ltd', sector: 'Pharma' },
  { symbol: 'STRIDES', name: 'Strides Pharma Science Ltd', sector: 'Pharma' },
  { symbol: 'GLENMARK', name: 'Glenmark Pharmaceuticals Ltd', sector: 'Pharma' },
  { symbol: 'NATCOPHARM', name: 'Natco Pharma Ltd', sector: 'Pharma' },
  { symbol: 'SEQUENT', name: 'Sequent Scientific Ltd', sector: 'Pharma' },
  { symbol: 'SUVEN', name: 'Suven Life Sciences Ltd', sector: 'Pharma' },
  { symbol: 'LAURUSLABS', name: 'Laurus Labs Ltd', sector: 'Pharma' },
  { symbol: 'SOLARA', name: 'Solara Active Pharma Sciences Ltd', sector: 'Pharma' },
  { symbol: 'CAPLIPOINT', name: 'Caplin Point Laboratories Ltd', sector: 'Pharma' },
  { symbol: 'THYROCARE', name: 'Thyrocare Technologies Ltd', sector: 'Healthcare' },
  { symbol: 'KRSNAA', name: 'Krsnaa Diagnostics Ltd', sector: 'Healthcare' },
  { symbol: 'RAINBOW', name: 'Rainbow Children\'s Medicare Ltd', sector: 'Healthcare' },
  { symbol: 'KPITTECH', name: 'KPIT Technologies Ltd', sector: 'IT' },
  { symbol: 'CYIENT', name: 'Cyient Ltd', sector: 'IT' },
  { symbol: 'LTTS', name: 'L&T Technology Services Ltd', sector: 'IT' },
  { symbol: 'SONATSOFTW', name: 'Sonata Software Ltd', sector: 'IT' },
  { symbol: 'ZENSAR', name: 'Zensar Technologies Ltd', sector: 'IT' },
  { symbol: 'RAMPGREEN', name: 'Ramco Systems Ltd', sector: 'IT' },
  { symbol: 'NEWGEN', name: 'Newgen Software Technologies Ltd', sector: 'IT' },
  { symbol: 'INTELLECT', name: 'Intellect Design Arena Ltd', sector: 'IT' },
  { symbol: 'MASTEK', name: 'Mastek Ltd', sector: 'IT' },
  { symbol: 'BIRLASOFT', name: 'Birlasoft Ltd', sector: 'IT' },
  { symbol: 'OFSS', name: 'Oracle Financial Services Software Ltd', sector: 'IT' },
  { symbol: 'POLYCAB', name: 'Polycab India Ltd', sector: 'Cables' },
  { symbol: 'KEI', name: 'KEI Industries Ltd', sector: 'Cables' },
  { symbol: 'FINOLEX', name: 'Finolex Cables Ltd', sector: 'Cables' },
  { symbol: 'DELTACORP', name: 'Delta Corp Ltd', sector: 'Entertainment' },
  { symbol: 'INOXLEISUR', name: 'INOX Leisure Ltd', sector: 'Entertainment' },
  { symbol: 'SUNTV', name: 'Sun TV Network Ltd', sector: 'Media' },
  { symbol: 'ZEEL', name: 'Zee Entertainment Enterprises Ltd', sector: 'Media' },
  { symbol: 'NETWORK18', name: 'Network18 Media & Investments Ltd', sector: 'Media' },
  { symbol: 'TVTODAY', name: 'TV Today Network Ltd', sector: 'Media' },
  { symbol: 'HATHWAY', name: 'Hathway Cable & Datacom Ltd', sector: 'Media' },
  { symbol: 'SITI', name: 'Siti Networks Ltd', sector: 'Media' },
  { symbol: 'SPICEJET', name: 'SpiceJet Ltd', sector: 'Aviation' },
  { symbol: 'JETAIRWAYS', name: 'Jet Airways (India) Ltd', sector: 'Aviation' },
  { symbol: 'GMDCLTD', name: 'Gujarat Mineral Development Corporation Ltd', sector: 'Mining' },
  { symbol: 'MOIL', name: 'MOIL Ltd', sector: 'Mining' },
  { symbol: 'NATIONALUM', name: 'National Aluminium Company Ltd', sector: 'Metals' },
  { symbol: 'RATNAMANI', name: 'Ratnamani Metals & Tubes Ltd', sector: 'Metals' },
  { symbol: 'WELCORP', name: 'Welspun Corp Ltd', sector: 'Metals' },
  { symbol: 'WELSPUNIND', name: 'Welspun India Ltd', sector: 'Textile' },
  { symbol: 'TRIDENT', name: 'Trident Ltd', sector: 'Textile' },
  { symbol: 'VARDHMAN', name: 'Vardhman Textiles Ltd', sector: 'Textile' },
  { symbol: 'CENTURYTEX', name: 'Century Textiles & Industries Ltd', sector: 'Textile' },
  { symbol: 'RAYMOND', name: 'Raymond Ltd', sector: 'Textile' },
  { symbol: 'ARVIND', name: 'Arvind Ltd', sector: 'Textile' },
  { symbol: 'GRASIM', name: 'Grasim Industries Ltd', sector: 'Textile' },
  { symbol: 'SRTRANSFIN', name: 'Shriram Transport Finance Company Ltd', sector: 'Finance' },
  { symbol: 'MANAPPURAM', name: 'Manappuram Finance Ltd', sector: 'Finance' },
  { symbol: 'EDELWEISS', name: 'Edelweiss Financial Services Ltd', sector: 'Finance' },
  { symbol: 'MOTILALOFS', name: 'Motilal Oswal Financial Services Ltd', sector: 'Finance' },
  { symbol: 'ANGELONE', name: 'Angel One Ltd', sector: 'Finance' },
  { symbol: 'IIFL', name: 'India Infoline Finance Ltd', sector: 'Finance' },
  { symbol: 'CAPFIRST', name: 'Capital First Ltd', sector: 'Finance' },
  { symbol: 'UJJIVAN', name: 'Ujjivan Financial Services Ltd', sector: 'Finance' },
  { symbol: 'EQUITAS', name: 'Equitas Holdings Ltd', sector: 'Finance' },
  { symbol: 'CREDITACC', name: 'Credit Access Grameen Ltd', sector: 'Finance' },
  { symbol: 'SPANDANA', name: 'Spandana Sphoorty Financial Ltd', sector: 'Finance' },
  { symbol: 'NAUKRI', name: 'Info Edge (India) Ltd', sector: 'Technology' },
  { symbol: 'JUSTDIAL', name: 'Just Dial Ltd', sector: 'Technology' },
  { symbol: 'MATRIMONY', name: 'Matrimony.com Ltd', sector: 'Technology' },
  { symbol: 'ROUTE', name: 'Route Mobile Ltd', sector: 'Technology' },
  { symbol: 'TANLA', name: 'Tanla Platforms Ltd', sector: 'Technology' },
  { symbol: 'RATEGAIN', name: 'RateGain Travel Technologies Ltd', sector: 'Technology' },
  { symbol: 'EASEMYTRIP', name: 'Easy Trip Planners Ltd', sector: 'Technology' },
  { symbol: 'IRCON', name: 'Ircon International Ltd', sector: 'Construction' },
  { symbol: 'RITES', name: 'RITES Ltd', sector: 'Construction' },
  { symbol: 'RAILTEL', name: 'RailTel Corporation of India Ltd', sector: 'Telecom' },
  { symbol: 'MAZAGON', name: 'Mazagon Dock Shipbuilders Ltd', sector: 'Defense' },
  { symbol: 'BEL', name: 'Bharat Electronics Ltd', sector: 'Defense' },
  { symbol: 'HAL', name: 'Hindustan Aeronautics Ltd', sector: 'Defense' },
  { symbol: 'BEML', name: 'BEML Ltd', sector: 'Defense' },
  { symbol: 'COCHINSHIP', name: 'Cochin Shipyard Ltd', sector: 'Defense' },
  { symbol: 'GRSE', name: 'Garden Reach Shipbuilders & Engineers Ltd', sector: 'Defense' },
  { symbol: 'MIDHANI', name: 'Mishra Dhatu Nigam Ltd', sector: 'Defense' },
  { symbol: 'NHPC', name: 'NHPC Ltd', sector: 'Power' },
  { symbol: 'SJVN', name: 'SJVN Ltd', sector: 'Power' },
  { symbol: 'THERMAX', name: 'Thermax Ltd', sector: 'Power' },
  { symbol: 'BHEL', name: 'Bharat Heavy Electricals Ltd', sector: 'Power' },
  { symbol: 'CESC', name: 'CESC Ltd', sector: 'Power' },
  { symbol: 'TORNTPOWER', name: 'Torrent Power Ltd', sector: 'Power' },
  { symbol: 'JSPL', name: 'Jindal Steel & Power Ltd', sector: 'Power' },
  { symbol: 'RENUKA', name: 'Shree Renuka Sugars Ltd', sector: 'Sugar' },
  { symbol: 'BALRAMCHIN', name: 'Balrampur Chini Mills Ltd', sector: 'Sugar' },
  { symbol: 'DHAMPUR', name: 'Dhampur Sugar Mills Ltd', sector: 'Sugar' },
  { symbol: 'DWARIKESH', name: 'Dwarikesh Sugar Industries Ltd', sector: 'Sugar' },
  { symbol: 'BAJAJHIND', name: 'Bajaj Hindusthan Sugar Ltd', sector: 'Sugar' },
  
  // Additional Small & Mid Cap Stocks
  { symbol: 'ASTRAL', name: 'Astral Ltd', sector: 'Building Materials' },
  { symbol: 'CERA', name: 'Cera Sanitaryware Ltd', sector: 'Building Materials' },
  { symbol: 'KAJARIA', name: 'Kajaria Ceramics Ltd', sector: 'Building Materials' },
  { symbol: 'SOMANY', name: 'Somany Ceramics Ltd', sector: 'Building Materials' },
  { symbol: 'HINDWARE', name: 'Hindware Home Innovation Ltd', sector: 'Building Materials' },
  { symbol: 'CARBORUNIV', name: 'Carborundum Universal Ltd', sector: 'Abrasives' },
  { symbol: 'GRINDWELL', name: 'Grindwell Norton Ltd', sector: 'Abrasives' },
  { symbol: 'TIMKEN', name: 'Timken India Ltd', sector: 'Bearings' },
  { symbol: 'SCHAEFFLER', name: 'Schaeffler India Ltd', sector: 'Bearings' },
  { symbol: 'SKFINDIA', name: 'SKF India Ltd', sector: 'Bearings' },
  { symbol: 'NBCC', name: 'NBCC (India) Ltd', sector: 'Construction' },
  { symbol: 'JKPAPER', name: 'JK Paper Ltd', sector: 'Paper' },
  { symbol: 'TNPL', name: 'Tamil Nadu Newsprint & Papers Ltd', sector: 'Paper' },
  { symbol: 'WESTPAPER', name: 'West Coast Paper Mills Ltd', sector: 'Paper' },
  { symbol: 'SESAGOA', name: 'Sesa Goa Ltd', sector: 'Mining' },
  { symbol: 'HINDZINC', name: 'Hindustan Zinc Ltd', sector: 'Metals' },
  { symbol: 'COPPER', name: 'Hindustan Copper Ltd', sector: 'Metals' },
  { symbol: 'ALUMINUM', name: 'Aluminium Industries Ltd', sector: 'Metals' },
  { symbol: 'JSWENERGY', name: 'JSW Energy Ltd', sector: 'Power' },
  { symbol: 'ADANIPOWER', name: 'Adani Power Ltd', sector: 'Power' },
  { symbol: 'RELPOWER', name: 'Reliance Power Ltd', sector: 'Power' },
  { symbol: 'JPPOWER', name: 'Jaiprakash Power Ventures Ltd', sector: 'Power' },
  { symbol: 'SUZLON', name: 'Suzlon Energy Ltd', sector: 'Power' },
  { symbol: 'RPOWER', name: 'Reliance Power Ltd', sector: 'Power' },
  { symbol: 'ORIENTREF', name: 'Oriental Refinery Ltd', sector: 'Energy' },
  { symbol: 'MRPL', name: 'Mangalore Refinery and Petrochemicals Ltd', sector: 'Energy' },
  { symbol: 'HINDPETRO', name: 'Hindustan Petroleum Corporation Ltd', sector: 'Energy' },
  { symbol: 'PETRONET', name: 'Petronet LNG Ltd', sector: 'Energy' },
  { symbol: 'GSPL', name: 'Gujarat State Petronet Ltd', sector: 'Energy' },
  { symbol: 'IGL', name: 'Indraprastha Gas Ltd', sector: 'Energy' },
  { symbol: 'MGL', name: 'Mahanagar Gas Ltd', sector: 'Energy' },
  { symbol: 'GUJGASLTD', name: 'Gujarat Gas Ltd', sector: 'Energy' },
  { symbol: 'ATGL', name: 'Adani Total Gas Ltd', sector: 'Energy' },
  { symbol: 'AEGISCHEM', name: 'Aegis Logistics Ltd', sector: 'Logistics' },
  { symbol: 'ALLCARGO', name: 'Allcargo Logistics Ltd', sector: 'Logistics' },
  { symbol: 'GATI', name: 'Gati Ltd', sector: 'Logistics' },
  { symbol: 'MAHLOG', name: 'Mahindra Logistics Ltd', sector: 'Logistics' },
  { symbol: 'TCI', name: 'Transport Corporation of India Ltd', sector: 'Logistics' },
  { symbol: 'BLUEDART', name: 'Blue Dart Express Ltd', sector: 'Logistics' },
  { symbol: 'DELHIVERY', name: 'Delhivery Ltd', sector: 'Logistics' },
  { symbol: 'FRETAIL', name: 'Future Retail Ltd', sector: 'Retail' },
  { symbol: 'PANTALOONS', name: 'Pantaloons Fashion & Retail Ltd', sector: 'Retail' },
  { symbol: 'LIFESTYLE', name: 'Lifestyle International Pvt Ltd', sector: 'Retail' },
  { symbol: 'VMART', name: 'V-Mart Retail Ltd', sector: 'Retail' },
  { symbol: 'ADITYA', name: 'Aditya Birla Fashion and Retail Ltd', sector: 'Retail' },
  { symbol: 'TCNSBRANDS', name: 'TCNS Clothing Co Ltd', sector: 'Retail' },
  { symbol: 'RTNINFRA', name: 'RattanIndia Infrastructure Ltd', sector: 'Infrastructure' },
  { symbol: 'JPASSOCIAT', name: 'Jaiprakash Associates Ltd', sector: 'Infrastructure' },
  { symbol: 'LAXMIMACH', name: 'Lakshmi Machine Works Ltd', sector: 'Engineering' },
  { symbol: 'TEXRAIL', name: 'Texmaco Rail & Engineering Ltd', sector: 'Engineering' },
  { symbol: 'TITAGARH', name: 'Titagarh Wagons Ltd', sector: 'Engineering' },
  { symbol: 'KALPATPOWR', name: 'Kalpataru Power Transmission Ltd', sector: 'Engineering' },
  { symbol: 'KEC', name: 'KEC International Ltd', sector: 'Engineering' },
  { symbol: 'THERMAX', name: 'Thermax Ltd', sector: 'Engineering' },
  { symbol: 'BHEL', name: 'Bharat Heavy Electricals Ltd', sector: 'Engineering' },
  { symbol: 'CUMMINS', name: 'Cummins India Ltd', sector: 'Engineering' },
  { symbol: 'ABB', name: 'ABB India Ltd', sector: 'Engineering' },
  { symbol: 'SCHNEIDER', name: 'Schneider Electric Infrastructure Ltd', sector: 'Engineering' },
  { symbol: 'LTFOODS', name: 'LT Foods Ltd', sector: 'Food Processing' },
  { symbol: 'KRBL', name: 'KRBL Ltd', sector: 'Food Processing' },
  { symbol: 'KOHINOOR', name: 'Kohinoor Foods Ltd', sector: 'Food Processing' },
  { symbol: 'USHAMART', name: 'Usha Martin Ltd', sector: 'Food Processing' },
  { symbol: 'VADILALIND', name: 'Vadilal Industries Ltd', sector: 'Food Processing' },
  { symbol: 'HATSUN', name: 'Hatsun Agro Product Ltd', sector: 'Food Processing' },
  { symbol: 'HERITAGE', name: 'Heritage Foods Ltd', sector: 'Food Processing' },
  { symbol: 'KWALITY', name: 'Kwality Ltd', sector: 'Food Processing' },
  { symbol: 'PARAG', name: 'Parag Milk Foods Ltd', sector: 'Food Processing' },
  { symbol: 'DODLA', name: 'Dodla Dairy Ltd', sector: 'Food Processing' },
  { symbol: 'PGHH', name: 'Procter & Gamble Hygiene & Health Care Ltd', sector: 'FMCG' },
  { symbol: 'GODREJIND', name: 'Godrej Industries Ltd', sector: 'FMCG' },
  { symbol: 'BAJAJCON', name: 'Bajaj Consumer Care Ltd', sector: 'FMCG' },
  { symbol: 'JYOTHYLAB', name: 'Jyothy Labs Ltd', sector: 'FMCG' },
  { symbol: 'VIPIND', name: 'VIP Industries Ltd', sector: 'Consumer Goods' },
  { symbol: 'SYMPHONY', name: 'Symphony Ltd', sector: 'Consumer Goods' },
  { symbol: 'ORIENTELEC', name: 'Orient Electric Ltd', sector: 'Consumer Goods' },
  { symbol: 'BAJAJELECTR', name: 'Bajaj Electricals Ltd', sector: 'Consumer Goods' },
  { symbol: 'RAJESHEXPO', name: 'Rajesh Exports Ltd', sector: 'Gems & Jewellery' },
  { symbol: 'THANGAMAYL', name: 'Thangamayil Jewellery Ltd', sector: 'Gems & Jewellery' },
  { symbol: 'PCJEWELLER', name: 'PC Jeweller Ltd', sector: 'Gems & Jewellery' },
  { symbol: 'GITANJALI', name: 'Gitanjali Gems Ltd', sector: 'Gems & Jewellery' },
  { symbol: 'KALYAN', name: 'Kalyan Jewellers India Ltd', sector: 'Gems & Jewellery' },
  { symbol: 'SENCO', name: 'Senco Gold Ltd', sector: 'Gems & Jewellery' },
  { symbol: 'PFIZER', name: 'Pfizer Ltd', sector: 'Pharma' },
  { symbol: 'GLAXO', name: 'GlaxoSmithKline Pharmaceuticals Ltd', sector: 'Pharma' },
  { symbol: 'SANOFI', name: 'Sanofi India Ltd', sector: 'Pharma' },
  { symbol: 'NOVARTIS', name: 'Novartis India Ltd', sector: 'Pharma' },
  { symbol: 'ABBOTT', name: 'Abbott India Ltd', sector: 'Pharma' },
  { symbol: 'MERCK', name: 'Merck Ltd', sector: 'Pharma' },
  { symbol: 'WOCKPHARMA', name: 'Wockhardt Ltd', sector: 'Pharma' },
  { symbol: 'PIRAMAL', name: 'Piramal Enterprises Ltd', sector: 'Pharma' },
  { symbol: 'ERIS', name: 'Eris Lifesciences Ltd', sector: 'Pharma' },
  { symbol: 'MANKIND', name: 'Mankind Pharma Ltd', sector: 'Pharma' },
  { symbol: 'ZYDUSWELL', name: 'Zydus Wellness Ltd', sector: 'Pharma' },
  { symbol: 'STARHEALTH', name: 'Star Health and Allied Insurance Company Ltd', sector: 'Insurance' },
  { symbol: 'NIACL', name: 'New India Assurance Company Ltd', sector: 'Insurance' },
  { symbol: 'ORIENTALINS', name: 'Oriental Insurance Company Ltd', sector: 'Insurance' },
  { symbol: 'UIICL', name: 'United India Insurance Company Ltd', sector: 'Insurance' },
  { symbol: 'NATIONALINS', name: 'National Insurance Company Ltd', sector: 'Insurance' },
  { symbol: 'RELIGARE', name: 'Religare Enterprises Ltd', sector: 'Finance' },
  { symbol: 'DHFL', name: 'Dewan Housing Finance Corporation Ltd', sector: 'Finance' },
  { symbol: 'CANFINHOME', name: 'Can Fin Homes Ltd', sector: 'Finance' },
  { symbol: 'REPCO', name: 'Repco Home Finance Ltd', sector: 'Finance' },
  { symbol: 'GRUH', name: 'Gruh Finance Ltd', sector: 'Finance' },
  { symbol: 'HUDCO', name: 'Housing & Urban Development Corporation Ltd', sector: 'Finance' },
  { symbol: 'INDIAHOUSING', name: 'India Home Loan Ltd', sector: 'Finance' },
]

async function syncStocks() {
  try {
    console.log('Connecting to database...')
    await connectDB()

    console.log(`Syncing ${NSE_STOCKS.length} stocks...`)

    let upserted = 0
    for (const stock of NSE_STOCKS) {
      await (Stock as any).findOneAndUpdate(
        { symbol: stock.symbol },
        {
          symbol: stock.symbol,
          name: stock.name,
          sector: stock.sector,
          exchange: 'NSE',
          active: true,
        },
        { upsert: true }
      )

      upserted++
      if (upserted % 20 === 0) {
        console.log(`Upserted ${upserted} stocks...`)
      }
    }

    console.log(`✓ Successfully synced ${upserted} stocks`)
    process.exit(0)
  } catch (error) {
    console.error('Sync failed:', error)
    process.exit(1)
  }
}

syncStocks()
